services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgrespw
    ports:
      - 5222:5432
#    volumes:
#      - E:/DockerVolume/postgresql:/var/lib/postgresql/data
#  rabbitmq:
#    image: rabbitmq:3-management-alpine
#    container_name: rabbitmq
#    ports:
#      - "5672:5672"
#      - "15672:15672"
  docmanagement-svc:
    image: doctorapp/docmanagement-svc:latest
    build: 
      context: .
      dockerfile: DocumentManagement/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5111
      - ConnectionStrings__DefaultConnection=Server=postgres;User Id=postgres;Password=postgrespw;Database=docmanagement
      - StorageSettings__BasePath=/DocumentStorage
    ports:
      - 5333:5111
    depends_on:
      - postgres
#      - rabbitmq
    volumes:
      - E:/DockerVolume/DocumentStorage:/DocumentStorage