global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'docmanagement-svc'
    scrape_interval: 5s
    static_configs:
      - targets: ['docmanagement-svc:8080']
  - job_name: 'patients-svc'
    scrape_interval: 5s
    static_configs:
      - targets: ['patients-svc:8080']