// <auto-generated />
using System;
using Dme.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dme.Infrastructure.Migrations
{
    [DbContext(typeof(DmeDbContext))]
    partial class DmeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dme.Domain.Models.Consultations", b =>
                {
                    b.Property<Guid>("ConsultationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int?>("CardiacFrequency")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ConsultationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FkIdDme")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Height")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<Guid>("LastModifiedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("NextConsultationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("PressureArterial")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<string>("ReasonOfVisit")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("SaturationOxygen")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Symptoms")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal?>("Temperature")
                        .HasColumnType("decimal(5, 2)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Weight")
                        .HasColumnType("decimal(5, 2)");

                    b.HasKey("ConsultationId");

                    b.HasIndex("FkIdDme");

                    b.ToTable("Consultations", "Dme");
                });

            modelBuilder.Entity("Dme.Domain.Models.Diagnostics", b =>
                {
                    b.Property<Guid>("DiagnosticId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("FkIdConsultation")
                        .HasColumnType("uuid");

                    b.Property<string>("Results")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("TypeDiagnostic")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("DiagnosticId");

                    b.HasIndex("FkIdConsultation");

                    b.ToTable("Diagnostics", "Dme");
                });

            modelBuilder.Entity("Dme.Domain.Models.Dme", b =>
                {
                    b.Property<Guid>("DmeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AdditionalInformations")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("Created")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<Guid>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FkIdDoctor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("FkIdPatient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<DateTime?>("LastModified")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("(NOW())");

                    b.Property<Guid>("LastModifiedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.HasKey("DmeId");

                    b.ToTable("Dme", "Dme");
                });

            modelBuilder.Entity("Dme.Domain.Models.Treatments", b =>
                {
                    b.Property<Guid>("TreatmentsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("Dose")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("FkIdConsultation")
                        .HasColumnType("uuid");

                    b.Property<string>("Frequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Instructions")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Medicament")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("TreatmentsId");

                    b.HasIndex("FkIdConsultation");

                    b.ToTable("Treatments", "Dme");
                });

            modelBuilder.Entity("Dme.Domain.Models.Consultations", b =>
                {
                    b.HasOne("Dme.Domain.Models.Dme", "Dme")
                        .WithMany("Consultations")
                        .HasForeignKey("FkIdDme")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dme");
                });

            modelBuilder.Entity("Dme.Domain.Models.Diagnostics", b =>
                {
                    b.HasOne("Dme.Domain.Models.Consultations", "Consultation")
                        .WithMany("Diagnostics")
                        .HasForeignKey("FkIdConsultation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("Dme.Domain.Models.Treatments", b =>
                {
                    b.HasOne("Dme.Domain.Models.Consultations", "Consultation")
                        .WithMany("Treatments")
                        .HasForeignKey("FkIdConsultation")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Consultation");
                });

            modelBuilder.Entity("Dme.Domain.Models.Consultations", b =>
                {
                    b.Navigation("Diagnostics");

                    b.Navigation("Treatments");
                });

            modelBuilder.Entity("Dme.Domain.Models.Dme", b =>
                {
                    b.Navigation("Consultations");
                });
#pragma warning restore 612, 618
        }
    }
}
